= Chapter 3

== 3.1 Introduction to Docker Compose

. Talk through slides
. Installed as part of Docker Toolbox or github.com/docker/compose/releases
. `docker-compose -v`
. `docker-compose --help`. Explain `up`, `ps`, `down`, `scale`, `restart`, `port`

== 3.2 Docker Compose file

. Sample `docker-compose.yml`

```
version: '3'
services:
  web:
    image: jboss/wildfly
    volumes:
      - ~/deployments:/opt/jboss/wildfly/standalone/deployments
    ports:
      - 8080:8080
```

. Explain `web`, `image`, `volumes, `ports`
. Compare with Docker CLI

Run the commands:

```
docker-compose up -d
docker-compose logs -f
cp ~/workspaces/docker-for-java/chapter2/webapp.war ~/deployments
curl http://localhost:8080/webapp/resources/persons
docker-compose down
```

=== 3.3 Multi-container application

```
version: '3'
services:
  web:
    image: arungupta/couchbase-javaee:travel
    environment:
      - COUCHBASE_URI=db
    ports:
      - 8080:8080
      - 9990:9990
    depends_on:
      - db
  db:
    image: arungupta/couchbase:travel
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
```

. Two images `web` and `db`
. Explain `depdends_on` - container and app starting sequence
. `COUCHBASE_URI` - show code
. Start application: `docker-compose up -d`
. Show logs: `docker-compose logs -f`
. Access application: `curl http://localhost:8080/airlines/resources/airline`


== 3.4 Docker Compose options

=== Project name

By default, service names is <project-name>_<service-name>_<service-number>
Start using `docker-compose -p myapp up -d`
`docker-compose ps` shows no services
`docker-compose -p test ps` shows services

=== Default Override

Copy the following in `docker-compose.override.yml`:

```
version: "3"
services:
  web:
   ports:
     - 9080:8080
```

. Run application: `docker-compose --verbose up -d`. Explain how the files picked are shown.
. App now accessible at curl http://localhost:9080/webapp/resources/persons
. Shutdown using `docker-compose down`

== 3.5 Docker Compose options

=== Multiple files

Copy the following in `docker-compose.db.yml`:

```
version: '3'
services:
  db:
   image: arungupta/couchbase
   ports:
     - 8091:8091
```

Run the command: `docker-compose -f docker-compose.yml -f docker-compose.db.yml up -d`
See services: `docker-compose -f docker-compose.yml -f docker-compose.db.yml ps`
Shutdown: `docker-compose -f docker-compose.yml -f docker-compose.db.yml down`

=== Multiple files (override `image` and aggregate `ports`)

Use the original `docker-compose.yml`:

```
version: '3'
services:
  web:
    image: arungupta/couchbase-javaee:travel
    environment:
      - COUCHBASE_URI=db
    ports:
      - 8080:8080
      - 9990:9990
    depends_on:
      - db
  db:
    image: arungupta/couchbase:travel
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
```

Copy the following in `docker-compose.prod.yml`:

```
version: '3'
services:
  web:
    ports:
      - 80:8080
  db:
    image: couchbase/server
```

Run the command: `docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d`

=== Extending services

Only supported in v2

```
version: '2'
services:
  config:
    environment:
      AWS_ACCESS_KEY: XXXX
      AWS_SECRET_KEY: XXXX
```

```
version: '2'
services:
  web:
    extends:
      file: configuration.yml
      service: config
    image: jboss/wildfly
    volumes:
      - ~/deployments:/opt/jboss/wildfly/standalone/deployments
    ports:
      - 8080:8080
```

Start application: `docker-compose --verbose up -d`

