= Chapter 4

== 4.1 Introduction to Swarm mode

Slides only

. Single node swarm: `docker swarm init`
. Show information: `docker info`

== 4.2 Create multi-node Swarm mode cluster using Docker Machine

Slides

. `docker-machine -v`
. Use `swarm-machines.sh` to pre-create 6 Docker Machines `manager1`, `manager2`, `manager3`, `worker`, `worker2`, `worker3`
. Initialize swarm mode on `manager`:
+
```
docker-machine ssh manager1 \
        "docker swarm init \
        --listen-addr $(docker-machine ip manager1) \
        --advertise-addr $(docker-machine ip manager1)"
```
+
. Show list of nodes: `docker-machine ssh manager1 "docker node ls"`
. Get manager token: `docker-machine ssh manager1 "docker swarm join-token manager -q"`
. Get worker token: `docker-machine ssh manager1 "docker swarm join-token worker -q"`
. Manager 2 joins cluster:
+
```
docker-machine ssh manager2 \
        "docker swarm join \
        --token `docker-machine ssh manager1 "docker swarm join-token manager -q"` \
        --listen-addr $(docker-machine ip manager2) \
        --advertise-addr $(docker-machine ip manager2) \
        $(docker-machine ip manager1)"
```
+
. Show list of nodes: `docker-machine ssh manager1 "docker node ls"`
. Manager 3 joins cluster:
+
```
docker-machine ssh manager3 \
        "docker swarm join \
        --token `docker-machine ssh manager1 "docker swarm join-token manager -q"` \
        --listen-addr $(docker-machine ip manager3) \
        --advertise-addr $(docker-machine ip manager3) \
        $(docker-machine ip manager1)"
```
+
. Show list of nodes: `docker-machine ssh manager1 "docker node ls"`
. Worker 1 join cluster:
+
```
docker-machine ssh worker1 \
        "docker swarm join \
        --token `docker-machine ssh manager1 "docker swarm join-token worker -q"` \
        --listen-addr $(docker-machine ip worker1) \
        --advertise-addr $(docker-machine ip worker1) \
        $(docker-machine ip manager1)"
```
+
. Show list of nodes: `docker-machine ssh manager1 "docker node ls"`
. Worker 2 join cluster:
+
```
docker-machine ssh worker2 \
        "docker swarm join \
        --token `docker-machine ssh manager1 "docker swarm join-token worker -q"` \
        --listen-addr $(docker-machine ip worker2) \
        --advertise-addr $(docker-machine ip worker2) \
        $(docker-machine ip manager1)"
```
+
. Show list of nodes: `docker-machine ssh manager1 "docker node ls"`
. Worker 3 join cluster:
+
```
docker-machine ssh worker3 \
        "docker swarm join \
        --token `docker-machine ssh manager1 "docker swarm join-token worker -q"` \
        --listen-addr $(docker-machine ip worker3) \
        --advertise-addr $(docker-machine ip worker3) \
        $(docker-machine ip manager1)"
```
+
. Show list of nodes: `docker-machine ssh manager1 "docker node ls"`
. Show cluster information: `docker-machine ssh manager1 "docker info"`

== 4.3 Create multi-node Swarm mode cluster on AWS/Azure

Slides

. Launch the template and explain the creation and parameters
. Setup SSH tunnel: `ssh -NL localhost:2374:/var/run/docker.sock docker@<master>`
. Show cluster information: `docker -H localhost:2374 info`

=== 4.4 Deploying services to Swarm mode

Slides

==== Create service

. Create a replicated service: `docker service create --name web --replicas 3 -p 8080:8080 jboss/wildfly`
. List service and replicas: `docker service ls`
. Inspect service: `docker service inspect web`
. List containers: `docker container ls`

=== 4.5 Container or Node failure

Slides

==== Container failure

. Show the list of containers: `docker container ls`
. Kill a container: `docker container rm {cid}`
. Show how desired vs actual is reconciled: `docker container ls`

==== Node failure

. Show the list of nodes: `docker-machine ls`
. Stop a worker node: `docker-machine stop worker3`
. Show how desired vs actual is reconciled: `docker container ls`

=== 4.6 Scaling and rolling update of service

Slides

==== Scale service

. Scale service: `docker service scale web=6`
. List service and replicas: `docker service ls`

==== Rolling update of service

. Create 6 replicas of a service: `docker service create --name webapp --replicas 6 -p 8080:8080 arungupta/wildfly-app:1`
. Check service: `docker service ls`
. Check tasks in the service: `docker service ps webapp`. Show the version of image in each app.
. Access the application http://192.168.99.100:8080/app/index.jsp and show green background
. Rolling update service: `docker service update webapp --image arungupta/wildfly-app:2 --update-parallelism 2 --update-delay 10s`
. Check status every 5 secs: `docker service ps webapp`
. Access the application http://192.168.99.100:8080/app/index.jsp and show red background

=== 4.7 Node maintenance, label/constraints, global service

Slides

=== 4.8 Multi-container application on multi-host cluster

```
```



