= Chapter 4

== 4.1 Introduction to Swarm mode

Slides

. Single node swarm: `docker swarm init`
. Show options: `docker swarm --help`
. Show information: `docker info`
. Leave swarm: `docker swarm leave` and `docker swarm leave -f`

== 4.2 Create multi-node Swarm mode cluster using Docker Machine

Slides

. `docker-machine -v`
. Pre-create 6 Docker Machines using `swarm-machines.sh`
. Show list of machines: `docker-machine ls`
. Initialize swarm mode on `manager`:
+
```
docker-machine ssh manager1 \
        "docker swarm init \
        --listen-addr $(docker-machine ip manager1) \
        --advertise-addr $(docker-machine ip manager1)"
```
+
. Show list of nodes: `docker-machine ssh manager1 "docker node ls"`
. Get manager token: `docker-machine ssh manager1 "docker swarm join-token manager -q"`
. Get worker token: `docker-machine ssh manager1 "docker swarm join-token worker -q"`
. Manager 2 joins cluster:
+
```
docker-machine ssh manager2 \
        "docker swarm join \
        --token `docker-machine ssh manager1 "docker swarm join-token manager -q"` \
        --listen-addr $(docker-machine ip manager2) \
        --advertise-addr $(docker-machine ip manager2) \
        $(docker-machine ip manager1)"
```
+
. Show list of nodes: `docker-machine ssh manager1 "docker node ls"`
. Manager 3 joins cluster:
+
```
docker-machine ssh manager3 \
        "docker swarm join \
        --token `docker-machine ssh manager1 "docker swarm join-token manager -q"` \
        --listen-addr $(docker-machine ip manager3) \
        --advertise-addr $(docker-machine ip manager3) \
        $(docker-machine ip manager1)"
```
+
. Show list of nodes: `docker-machine ssh manager1 "docker node ls"`
. Worker 1 join cluster:
+
```
docker-machine ssh worker1 \
        "docker swarm join \
        --token `docker-machine ssh manager1 "docker swarm join-token worker -q"` \
        --listen-addr $(docker-machine ip worker1) \
        --advertise-addr $(docker-machine ip worker1) \
        $(docker-machine ip manager1)"
```
+
. Show list of nodes: `docker-machine ssh manager1 "docker node ls"`
. Worker 2 join cluster:
+
```
docker-machine ssh worker2 \
        "docker swarm join \
        --token `docker-machine ssh manager1 "docker swarm join-token worker -q"` \
        --listen-addr $(docker-machine ip worker2) \
        --advertise-addr $(docker-machine ip worker2) \
        $(docker-machine ip manager1)"
```
+
. Worker 3 join cluster:
+
```
docker-machine ssh worker3 \
        "docker swarm join \
        --token `docker-machine ssh manager1 "docker swarm join-token worker -q"` \
        --listen-addr $(docker-machine ip worker3) \
        --advertise-addr $(docker-machine ip worker3) \
        $(docker-machine ip manager1)"
```
+
. Show list of nodes: `docker-machine ssh manager1 "docker node ls"`
. Show cluster information: `docker-machine ssh manager1 "docker info"`

Alternatively, you can use `swarm-cluster-create.sh` script to create the cluster.

== 4.3 Deploying services to Swarm mode

Slides

=== Create service

. SSH to `manager1`: `docker-machine ssh manager1`
. Create a replicated service: `docker service create --name web --replicas 3 -p 8080:8080 jboss/wildfly`
. List service and replicas: `docker service ls`
. Inspect service: `docker service inspect web`
. List containers: `docker service ps web`

== 4.4 Container or Node failure

Slides

=== Container failure

. Show the list of containers: `docker container ls`
. Kill a container: `docker container rm {cid}`
. Show how desired vs actual is reconciled: `docker container ls`

=== Node failure

. Show the list of nodes: `docker-machine ls`
. Stop a worker node: `docker-machine stop worker3`
. Show how desired vs actual is reconciled: `docker container ls`

== 4.5 Scaling and rolling update of service

Slides

To be shown with Docker Machine cluster

=== Scale service

. Scale service: `docker service scale web=6`
. List service and replicas: `docker service ls`

=== Rolling update of service

. Create 6 replicas of a service: `docker service create --name webapp --replicas 6 -p 8080:8080 arungupta/wildfly-app:1`
. Check service: `docker service ls`
. Check tasks in the service: `docker service ps webapp`. Show the version of image in each app.
. Access the application http://192.168.99.100:8080/app/index.jsp and show green background
. Rolling update service: `docker service update webapp --image arungupta/wildfly-app:2 --update-parallelism 2 --update-delay 10s`
. Check status every 5 secs: `docker service ps webapp`
. Access the application http://192.168.99.100:8080/app/index.jsp and show red background

== 4.6 Multi-container application on multi-host cluster

Only to be used with Docker for AWS:

```
version: '3'
services:
  web:
    image: arungupta/couchbase-javaee:travel
    environment:
      - COUCHBASE_URI=db
    ports:
      - 8080:8080
      - 9990:9990
    depends_on:
      - db
  db:
    image: arungupta/couchbase:travel
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
```

. `docker stack deploy --compose-file=docker-compose.yml webapp`
. `docker stack ls`
. `docker service ls`
. `docker service ps webapp_web` - show the node where the container is running
. `docker service ps webapp_db` - show the node where the container is running
. `docker service logs webapp_web` - only works on experimental, verified using `docker info`
. Access the application `curl -v http://localhost:8080/airlines/resources/airline`

== 4.7 Node maintenance, label/constraints, global service

Slides only

== 4.8 Create multi-node Swarm mode cluster on AWS/Azure

Slides

. Launch the template and explain the creation and parameters
. Setup SSH tunnel: `ssh -NL localhost:2374:/var/run/docker.sock docker@<master>`
. Show cluster information: `docker -H localhost:2374 info`

